CREATE TABLE articles (
  article_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  title character varying(150) NOT NULL,
  content character varying(8000) NOT NULL,
  user_id integer
);

CREATE TABLE images (
  image_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  path character varying(250),
  article_id integer
);

CREATE TABLE users (
  user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  email character varying(254) NOT NULL,
  password character varying(32) NOT NULL
);

CREATE TABLE ratings (
  article_id integer,
  user_id integer,
  rating integer NOT NULL,
  PRIMARY KEY (article_id, user_id)
);

ALTER TABLE images ADD FOREIGN KEY (article_id) REFERENCES articles (article_id);

ALTER TABLE articles ADD FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE ratings ADD FOREIGN KEY (article_id) REFERENCES articles (article_id);

ALTER TABLE ratings ADD FOREIGN KEY (user_id) REFERENCES users (user_id);
